.catalog:
  name: Jenkins
  version: 2.32.3-rancher1
  description: |
    Jenkins CI management server.
  questions:
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should Jenkins listen on?"
    default: 8080
    required: true
  - variable: "volume_work"
    description: "Work volume to save jenkins data"
    label: "Work volume:"
    required: true
    default: "/var/lib/docker/jenkins-ci"
    type: "string"
  - variable: "hostname"
    type: "string"
    label: "LB hostname"
    description: "will be used in the LB config and name the host hostname.wds.io, will be needed to route 53"
    required: true
    default: "changeme.please"
  - variable: "plugins"
    type: "multiline"
    label: "List of Plugins"
    description: |
      List of plugins in the format <plugin_name>[:<version>]
      one entry per line.
    default: |
      credentials
      git
      git-client
      github
      github-api
      github-oauth
      greenballs
      junit
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm
jenkins-primary:
  metadata:
    plugins: |
      ${plugins}
  lb_config:
     port_rules:
     - hostname: ${hostname}.wds.io
       target_port: 8080
   health_check:
     healthy_threshold: 2
     response_timeout: 2000
     port: 8080
     unhealthy_threshold: 3
     initializing_timeout: 300000
     interval: 2000
     strategy: recreate
