.catalog:
  name: Jenkins
  version: 2.32.3-rancher1
  description: |
    Jenkins CI management server.
  questions:
    - variable: "version"
      label: "Version"
      description: "Jenkins Version"
      type: "string"
      default: "2.32.3"
      required: true
    - variable: "PORT"
      type: "int"
      label: "Port Number"
      description: "Which port should Jenkins listen on?"
      default: 8080
      required: true
    - variable: "volume_work"
      description: "Work volume to save jenkins data"
      label: "Work volume"
      required: true
      default: "/var/lib/docker/jenkins-ci"
      type: "string"
    - variable: "volume_size"
      description: "Size of jenkins work volume"
      label: "Volume Size (GB)"
      required: true
      default: "30"
      type: "int"
    - variable: "hostname"
      type: "string"
      label: "LB hostname"
      description: "will be used in the LB config and name the host hostname, will be needed to route 53"
      required: true
    - variable: "plugins"
      type: "multiline"
      label: "List of Plugins"
      description: |
        List of plugins in the format <plugin_name>[:<version>]
        one entry per line.
      default: |
        ace-editor:1.1
        ant:1.4
        antisamy-markup-formatter:1.5
        bouncycastle-api:2.16.0
        build-blocker-plugin:1.7.3
        build-pipeline-plugin:1.5.6
        conditional-buildstep:1.3.5
        cucumber-reports:3.5.1
        external-monitor-job:1.7
        htmlpublisher:1.12
        icon-shim:2.0.3
        javadoc:1.4
        jquery-detached:1.2.1
        jquery:1.11.2-0
        ldap:1.14
        matrix-auth:1.4
        maven-plugin:2.15.1
        pam-auth:1.3
        parameterized-trigger:2.33
        run-condition:1.0
        sauce-ondemand:1.161
        thinBackup:1.9
        windows-slaves:1.3.1
        workflow-api:2.12
        workflow-basic-steps:2.4
        workflow-cps:2.29
        workflow-job:2.10
        workflow-support:2.13
        credentials:2.1.13
        display-url-api:1.1.1
        git:3.1.0
        git-client:2.3.0
        github:1.26.1
        github-api:1.85
        github-oauth:0.25
        greenballs:1.15
        junit:1.20
        mailer:1.19
        matrix-project:1.8
        plain-credentials:1.4
        scm-api:2.1.0
        script-security:1.27
        ssh-credentials:1.13
        ssh-slaves:1.13
        structs:1.6
        swarm:3.3
        token-macro:2.0
        workflow-step-api:2.9
        workflow-scm-step:2.4
version: '2'
services:
  jenkins-primary:
    scale: 1
    metadata:
      plugins: |
        ${plugins}
    lb_config:
      port_rules:
        - hostname: ${hostname}
          target_port: ${PORT}
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: ${PORT}
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
  jenkins-plugins:
    scale: 1
  jenkins-datavolume:
    scale: 1
