.catalog:
  name: Jenkins
  version: 2.32.3-rancher1
  description: |
    Jenkins CI management server.
  questions:
    - variable: "version"
      label: "Version"
      description: "Jenkins Version"
      type: "string"
      default: "2.32.3"
      required: true
    - variable: "PORT"
      type: "int"
      label: "Port Number"
      description: "Which port should Jenkins listen on?"
      default: 8080
      required: true
    - variable: "volume_work"
      description: "Work volume to save jenkins data"
      label: "Work volume"
      required: true
      default: "/var/lib/docker/jenkins-ci"
      type: "string"
    - variable: "volume_size"
      description: "Size of jenkins work volume"
      label: "Volume Size (GB)"
      required: true
      default: "30"
      type: "int"
    - variable: "hostname"
      type: "string"
      label: "LB hostname"
      description: "will be used in the LB config and name the host hostname, will be needed to route 53"
      required: true
    - variable: "plugins"
      type: "multiline"
      label: "List of Plugins"
      description: |
        List of plugins in the format <plugin_name>[:<version>]
        one entry per line.
      default: |
        ace-editor:1.1
        ant:1.4
        antisamy-markup-formatter:1.5
        authentication-tokens:1.3
        blueocean-autofavorite:0.6
        blueocean-commons:1.0.0-rc1
        blueocean-config:1.0.0-rc1
        blueocean-dashboard:1.0.0-rc1
        blueocean-display-url:1.5.1
        blueocean-git-pipeline:1.0.0-rc1
        blueocean-github-pipeline:1.0.0-rc1
        blueocean-i18n:1.0.0-rc1
        blueocean-jwt:1.0.0-rc1
        blueocean-personalization:1.0.0-rc1
        blueocean-pipeline-api-impl:1.0.0-rc1
        blueocean-pipeline-editor:0.2-rc1
        blueocean-rest-impl:1.0.0-rc1
        blueocean-rest:1.0.0-rc1
        blueocean-web:1.0.0-rc1
        blueocean:1.0.0-rc1
        bouncycastle-api:2.16.0
        branch-api:2.0.8
        build-blocker-plugin:1.7.3
        build-pipeline-plugin:1.5.6
        cloudbees-folder:6.0.3
        conditional-buildstep:1.3.5
        credentials:2.1.13
        credentials-binding:1.10
        cucumber-reports:3.5.1
        display-url-api:1.1.1
        durable-task:1.13
        docker-workflow:1.10
        docker-commons:1.6
        external-monitor-job:1.7
        favorite:2.0.4
        git-client:2.3.0
        git-server:1.7
        git:3.1.0
        github-api:1.85
        github-branch-source:2.0.4
        github-oauth:0.25
        github-organization-folder:1.6
        github:1.26.1
        greenballs:1.15
        htmlpublisher:1.12
        icon-shim:2.0.3
        javadoc:1.4
        jackson2-api:2.7.3
        jquery-detached:1.2.1
        jquery:1.11.2-0
        junit:1.20
        ldap:1.14
        mailer:1.19
        matrix-auth:1.4
        matrix-project:1.8
        maven-plugin:2.15.1
        metrics:3.1.2.9
        pam-auth:1.3
        parameterized-trigger:2.33
        pipeline-github-lib:1.0
        pipeline-graph-analysis:1.3
        pipeline-input-step:2.5
        pipeline-model-api:1.1.1
        pipeline-model-definition:1.1.1
        pipeline-model-extensions:1.1.1
        pipeline-stage-step:2.2
        pipeline-stage-tags-metadata:1.1.1
        plain-credentials:1.4
        run-condition:1.0
        sauce-ondemand:1.161
        scm-api:2.1.0
        script-security:1.27
        ssh-credentials:1.13
        ssh-slaves:1.13
        structs:1.6
        swarm:3.3
        thinBackup:1.9
        token-macro:2.0
        variant:1.1
        windows-slaves:1.3.1
        workflow-api:2.12
        workflow-basic-steps:2.4
        workflow-cps-global-lib:2.7
        workflow-cps:2.29
        workflow-durable-task-step:2.10
        workflow-job:2.10
        workflow-multibranch:2.14
        workflow-scm-step:2.4
        workflow-step-api:2.9
        workflow-support:2.13
version: '2'
services:
  jenkins-primary:
    scale: 1
    metadata:
      plugins: |
        ${plugins}
    lb_config:
      port_rules:
        - hostname: ${hostname}
          target_port: ${PORT}
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: ${PORT}
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
  jenkins-plugins:
    scale: 1
  jenkins-datavolume:
    scale: 1
